name: Pull Request Workflow
on:
  pull_request:
    types: [opened, edited]

jobs:
  check-subscription:
    runs-on: ubuntu-latest
    outputs:
      subscription: ${{ steps.extract-subscription.outputs.subscription }}
    steps:
      - name: Extract Subscription Name
        id: extract-subscription
        run: |
          echo "Pull request body: ${{ github.event.pull_request.body }}"
          subscription=$(echo "${{ github.event.pull_request.body }}" | grep -oP '(?<=Subscription:).*')
          echo "Subscription name: $subscription"
          echo "subscription=$subscription" >> $GITHUB_OUTPUT

      - name: Use Subscription Name
        run: |
          echo "The extracted subscription name is: ${{ steps.extract-subscription.outputs.subscription }}"

  terraform_init_and_plan:
    name: "Terraform Init and Plan"
    needs: check-subscription
    runs-on: ubuntu-latest
    steps:
      - name: Use Subscription Name
        run: |
          echo "The extracted subscription name is: ${{ needs.check-subscription.outputs.subscription }} that is running in job2"
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: `## Terraform Plan Output\n\n`
                });