name: Pull Request Workflow
on:
  pull_request:
    types: [opened, edited]

jobs:
  check-subscription:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Subscription Name
        id: extract-subscription
        run: |
          echo "Pull request body: ${{ github.event.pull_request.body }}"
          subscription=$(echo "${{ github.event.pull_request.body }}" | grep -oP '(?<=Subscription:).*')
          echo "Subscription name: $subscription"
          echo "subscription=$(subscription)\n" >> $GITHUB_OUTPUT

      - name: Use Subscription Name
        run: |
          echo "The extracted subscription name is: ${{ steps.extract-subscription.outputs.subscription }}"